name: Build test

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cargo install cargo-deb

      - name: Build binary
        run: |
          cargo build

      - name: Build deb package
        run: |
          cargo deb

      - name: Upload deb package to artifacts
        uses: actions/upload-artifact@v4
        with:
          path: target/debian/*.deb
